name: Portal sync action
description: WIP Sync action for Konnect portal
runs:
  using: node20
  main: dist/index.js
branding:
  icon: edit-2
  color: orange
inputs:
  konnect_pat:
    description: Konnect authentication details
    required: true
